[project]
name = "thompson-sampling"
version = "0.1.0"
description = "Thompson sampling for Bayesian multi-armed bandit."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "scipy>=1.16.2",
    "tqdm>=4.67.1",
]


[tool.ruff]
line-length = 100
